
class DB():
  NAME = "HAuSE"
  
  class COLLECTIONS():
    COMMANDS = "COMMANDS"
  
COMMAND_CACHE_SIZE = 10

BUFFERED_TEMP_FILE_PATH = "/tmp/"
BUFFERED_TEMP_FILE_PREFIX = "HAuSE-temp"
BUFFERED_TEMP_LOCATION = BUFFERED_TEMP_FILE_PATH + BUFFERED_TEMP_FILE_PREFIX
BUFFERED_TEMP_FILES = 10

